version: '3'

services: 
  traefik: 
    restart: always
    image: traefik:v1.7
    container_name: traefik
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    environment: 
      - "TZ=Europe/Berlin"
    networks: 
      - traefik_proxy
      - default
  
  web:
    image: httpd:latest
    container_name: webpage
    volumes: 
      - /phu/webpage-commanderphu/:/usr/local/apache2/htdocs
    labels: 
      - "traefik.backend=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:phuonline.de"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks: 
      - traefik_proxy
networks: 
  traefik_proxy:
    external: 
      name: traefik_proxy
  default:
    driver: bridge
