version: '3'

services: 
  traefik: 
    restart: always
    image: traefik:v1.7
    container_name: traefik
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./certificate:/etc/certificate
    environment: 
      - "TZ=Europe/Berlin"
    networks: 
      - traefik_proxy
      - default
  
  web:
    image: httpd:latest
    container_name: webpage
    volumes: 
      - /phu/webpage/:/usr/local/apache2/htdocs
    labels: 
      - "traefik.backend=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:phuonline.de"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks: 
      - traefik_proxy

  gitlab:
    image: gitlab/gitlab-ce:lastest
    container_name: gitlab
    volumes: 
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab 
    labels: 
      - "traefik.backend=git"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:git.phuonline.de"
      - "traefik.port=80"
      - "traefik.port=443"
      - "traefik.port=22"
      - "traefik.docker.network=traefik_proxy"
    networks: 
      - traefik_proxy
  
  radicale:
    image: tomsquest/docker-radicale:amd64.2.1.11.0
    container_name: radicale
    ports: 
      - 5232:5232
    labels:
      - "traefik.backend=radicale"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dav.phuonline.de"
      - "traefik.port=5232"
      - "traefik.docker.network=traefik_proxy"
    networks: 
      - traefik_proxy

networks: 
  traefik_proxy:
    external: 
      name: traefik_proxy
  default:
    driver: bridge
