version: '3'

services: 
  traefik: 
    restart: always
    image: traefik:latest
    container_name: traefik
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
     