logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[docker]
  domain = "phuonline.de"
  watch = true
  exposedbydefault = false

 # Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certificate/cert.crt"
      keyFile = "/etc/certificate/cert.key"

 # Let's encrypt configuration
 # [acme]
 #  email="admin@phuonline.de"
 # storage="/etc/traefik/acme/acme.json"
 #  caServer="https://acme-staging-v02.api.letsencrypt.org/directory"
 #  entryPoint="https"
 #  acmeLogging=true
 #  OnHostRule=true
 #  [[acme.domains]]
 #     main ="phuonline.de"
 #  [[acme.domains]]
 #     main = "*.phuonline.de"
 #  [acme.httpChallenge]
 #    entryPoint = "http"
     

